var subject = require('./mystery.js')
var mock = require('mock-fs');
subject.inc(30,undefined);
subject.inc(30,10);
subject.inc(20,undefined);
subject.inc(20,10);
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":"text content"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":"text content2"},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":"text content2"},"pathContent":{"file1":"text content"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":"text content"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":"text content2"},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":"text content2"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":""},"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content"},"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":""},"path/fileExists":{"file1":"text content2"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content"},"path/fileExists":{"file1":"text content2"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":""},"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content"},"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":"text content2"},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":"text content2"}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""},"pathContent":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{"file1":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
subject.format('','','');
subject.format('','',{"shouldNormalize":true});
subject.blackListNumber('9191234567');
subject.blackListNumber('1001234567');
